// <auto-generated />
using System;
using KiteBotCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace KiteBotCore.Migrations
{
    [DbContext(typeof(KiteBotDbContext))]
    [Migration("20190401004005_GuildShineRemoval")]
    partial class GuildShineRemoval
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("KiteBotCore.Channel", b =>
                {
                    b.Property<long>("ChannelId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GuildForeignKey");

                    b.Property<string>("Name");

                    b.HasKey("ChannelId");

                    b.HasIndex("GuildForeignKey");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("KiteBotCore.Guild", b =>
                {
                    b.Property<long>("GuildId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("GuildId");

                    b.ToTable("Guilds");
                });

            modelBuilder.Entity("KiteBotCore.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("ChannelForeignKey");

                    b.Property<string>("Content");

                    b.Property<long>("UserForeignKey");

                    b.HasKey("MessageId");

                    b.HasIndex("ChannelForeignKey");

                    b.HasIndex("UserForeignKey");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("KiteBotCore.ShineBet", b =>
                {
                    b.Property<int>("ShineBetId")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Answer");

                    b.Property<bool>("DoubleDown");

                    b.Property<int>("ShineBetEventId");

                    b.Property<long?>("UserId");

                    b.HasKey("ShineBetId");

                    b.HasIndex("ShineBetEventId");

                    b.HasIndex("UserId");

                    b.ToTable("ShineBets");
                });

            modelBuilder.Entity("KiteBotCore.ShineBetEvent", b =>
                {
                    b.Property<int>("ShineBetEventId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BetAmount");

                    b.Property<bool?>("BetResult");

                    b.Property<long>("ChannelId");

                    b.Property<DateTimeOffset>("CreationDateTime");

                    b.Property<long>("OwnerUserUserId");

                    b.Property<string>("Question")
                        .IsRequired();

                    b.Property<TimeSpan>("TimeUntilClose");

                    b.HasKey("ShineBetEventId");

                    b.HasIndex("ChannelId");

                    b.HasIndex("OwnerUserUserId");

                    b.ToTable("ShineBetEvents");
                });

            modelBuilder.Entity("KiteBotCore.User", b =>
                {
                    b.Property<long>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("GuildForeignKey");

                    b.Property<DateTimeOffset?>("JoinedAt");

                    b.Property<DateTimeOffset>("LastActivityAt");

                    b.Property<string>("Name");

                    b.Property<int>("Shines");

                    b.HasKey("UserId");

                    b.HasIndex("GuildForeignKey");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("KiteBotCore.UserColorRoles", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<long>("RoleId");

                    b.Property<DateTimeOffset?>("RemovalAt");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserColorRoles");
                });

            modelBuilder.Entity("KiteBotCore.Channel", b =>
                {
                    b.HasOne("KiteBotCore.Guild", "Guild")
                        .WithMany("Channels")
                        .HasForeignKey("GuildForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KiteBotCore.Message", b =>
                {
                    b.HasOne("KiteBotCore.Channel", "Channel")
                        .WithMany("Messages")
                        .HasForeignKey("ChannelForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KiteBotCore.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KiteBotCore.ShineBet", b =>
                {
                    b.HasOne("KiteBotCore.ShineBetEvent", "ShineBetEvent")
                        .WithMany("ShineBets")
                        .HasForeignKey("ShineBetEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KiteBotCore.User", "User")
                        .WithMany("Bets")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("KiteBotCore.ShineBetEvent", b =>
                {
                    b.HasOne("KiteBotCore.Channel", "Channel")
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("KiteBotCore.User", "OwnerUser")
                        .WithMany()
                        .HasForeignKey("OwnerUserUserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KiteBotCore.User", b =>
                {
                    b.HasOne("KiteBotCore.Guild", "Guild")
                        .WithMany("Users")
                        .HasForeignKey("GuildForeignKey")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("KiteBotCore.UserColorRoles", b =>
                {
                    b.HasOne("KiteBotCore.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
